### ISSUE TITLE
tincture handling of imported charges.svg

### ISSUE THREAD

**Issue by ghost** [heraldry/armory#1]
I have problems setting the colors of imported charges properly. I believe this is most likely a documentation issue because the importing procedure to set primary and infill tinctures is not described. I imported an [escarboucle](https://en.wikipedia.org/wiki/Carbuncle_(heraldry)) in the form of an SVG from Wikipedia: https://no.wikipedia.org/wiki/Fil:Escarboucle.svg but I have no clue how to set the size properly or how to define the colors (fill and outline) in a way that a user can choose and that is shows by default an outline sable and a transparent fill.

**Comment by or** [comment]
You're right, the documentation is severely lacking right now.
I'm in the process of rewriting the UI to fix some things that grew messy, so the interface will likely change quite a bit, but in the meantime check out this release screenshot:
https://heraldry.digital/img/2021-05-09-release-update.png at the bottom left you see an example for a charge.

The idea is that you edit the SVG in a program like Inkscape (or others) and give all the bits you want to tincture distinct colours. In the excarboucle case you probably can just give it one colour.

When you upload it in the interface the UI should have found all different colours and provide a select field to identify them. The most important two there are "outline" and "primary". Once that is done and saved you can add the charge to any arms. The primary colour will be replaced by the field in the charge and tincture modifiers (armed, langued, legged, etc.) can be set arbitrarily.
For the SVG you posted you probably only have to set black to "outline" and white to "primary". Actually, I'd also recommend changing the white to something non-white in the source SVG, easier to see, and white is a bit special, which is why you saw it as transparent.

You shouldn't have to resize anything, the program should auto-resize as needed. It's recommended to adjust the SVG document size to only contain the relevant charge, tho. So there are no empty borders around it or anything, but your SVG looks good for that already.

**Comment by or** [comment]
I hope the answer was sufficient. Re-open if necessary.
