### ISSUE TITLE
feature request "en soleil"

### ISSUE THREAD

**Issue by ghost** [heraldry/armory#2]
Fimbriation is fully implemented but "[en soleil](https://www.collinsdictionary.com/dictionary/english/en-soleil)" with its different versions so far not. One can work around it with a sun in the background, but that would not blazon correctly. Most known examples are the [Yorkshire roses en soleil](https://commons.wikimedia.org/wiki/Category:York_Herald_of_Arms_in_Ordinary).

**Comment by or** [comment]
Interesting, I hadn't seen that before. Would be nice to have, I've tagged this as feature request, thanks.

Heads up regarding the blazonry: it's been neglected a lot. It won't blazon a lot of the features or do it in a bad way. This will become a focus again someday, but for now I'll have to treat it with low priority.

**Comment by ghost** [comment]
I do understand that. I think it is impossible to blazon everything correctly, especially with all the other countries (e.g. like mine, Germany) having very different descriptions or don't allow certain items vice versa.

**Comment by or** [comment]
Yes, German is going to be a whole different beast, but it is planned.

One feature that hopefully will solve a lot of special cases is to add a manual blazonry override to most elements. That should take care of a lot of special cases. It might be useful for this as well, e.g. adding "en soleil" to the top charge, forcing the sun charge not to be blazoned at all, but this actually might be a useful feature on its own, so the sun moves with the charge, etc.

**Comment by or** [comment]
I've reached this TODO again and considered some ways to implement it, but decided that the easiest thing is really just to use a sun charge behind it, like you said. I realize it's a little annoying, having to edit two charges to match the size, but that'll always be necessary because the system can't know what looks good with the actual charge being selected, and doing that as a special feature inside the charge options would complicate matters a lot.

The blazonry now can be adjusted with the "manual blazon" text that can be set for every element, so that shouldn't be an issue anymore.

The only remaining drawback I can think of is a single fimbriation setting that uses sun + charge as the edge, rather than fimbriating the sun and the charge. But this also would be too complicated as part of charge options, so I recommend for that case to just make an SVG charge outside of HD and add it as a new charge, then the fimbriation can be done properly.
